### ISSUE TITLE
Naming issue  - sonar rule violation

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/cobigen#1370] opened 2021-07-15 11:46 UTC
Sonar issue is on:
public class AbstractUserUc extends AbstractUc {

**Reason**:
If a superclass has Uc.*Impl as suffix, then the subclass should also have Uc.*Impl as suffix.

Non-abstract use-case classes must begin with Uc, end with Impl and implement an interface with the same name except the suffix Impl.

**Rule**
This rule checks that non-abstract classes inheriting from AbstractUc begin with Uc, end with Impl and implement an interface with the same name except the suffix Impl.

Hint:
public class UcAbstractUserImpl extends AbstractUc implements UcUser {}

**Comment by hohwille** [comment] 2021-07-16 12:01
My first question is why CobiGen ever invented these abstract classes. Seems overengineered and we could question if we simplify this. I see that we better need to align and design the templates together with the stacks. Is CobiGen Team the owner and maintainer of the templates for devon4j or is devon4j team responsible? Maybe both but currently this is unclear.

We can save a minimal redundancy here such as e.g. injection of DAO/Repo but IMHO it is not worth the extra abstract class in between.

Second in case we want to keep this abstract use-case we have two options:
* change the naming as suggested by @sujith-mn - see https://github.com/devonfw/cobigen/blob/master/cobigen-templates/templates-devon4j/src/main/templates/crud_java_server_app_complex/templates/java/%24%7Bvariables.rootPackage%7D/%24%7Bvariables.component%7D/logic/base/usecase/Abstract%24%7Bvariables.entityName%7DUc.java.ftl#L11 and https://github.com/devonfw/cobigen/blob/master/cobigen-templates/templates-devon4j/src/main/templates/crud_java_server_app_complex/templates/java/%24%7Bvariables.rootPackage%7D/%24%7Bvariables.component%7D/logic/impl/usecase/UcManage%24%7Bvariables.entityName%7DImpl.java.ftl#L28, etc.
* change sonar-devon4j-plugin to be compliant - My actual goal was that use-cases are properly named and carry the `Uc` in the name so it becomes clear that it is a use-case, but `AbstractUserUc` is perfectly fine to me so I see that the rule is simply implementd inappropriate: https://github.com/devonfw/sonar-devon4j-plugin/blob/master/src/main/java/com/devonfw/ide/sonarqube/common/impl/check/naming/DevonNamingConventionClassExtendsClassUcImplCheck.java - so after reading this I get the impression that `AbstractUserUc` is missing the `abstract` keyword and that is all that is wrong here. Would you agree?

**Comment by maybeec** [comment] 2021-07-16 19:15
This stuff could be really old generated code which remains functional but might have been changed from code architecture in newest versions of devon4j.

Feel free to change it accordingly. We don't want to be the owners of the templates. Also devon4ng templates have never been maintained by the cobigen team.

I think it's time to get rid of the mono templates project to distribute code ownership for template snippets.

**Comment by hohwille** [comment] 2021-07-20 08:42
So the easy things first:
* Robert or whoever is affected by this issue can simply add `abstract` keyword to `AbstractUserUc` and the issue is resolved.
* I will change the CobiGen Template to have this missing `abstract` keyword included and the issue is also fixed. Will surely take some time to release those changes...

**Comment by hohwille** [comment] 2021-07-20 08:45
IMHO done, hence I am closing. In case I am missing anything, please reopen with explanation.

**Closed by hohwille** 2021-07-20 08:45 UTC
Labels: bug
