### ISSUE TITLE
CobiGen CLI "generate" command should support backward slashes in path input on Windows CMD

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1421] opened 2021-11-10 13:14 UTC
As a CobiGen CLI user on Windows CMD, I want to use backward slashes for my generate input path so that I can use auto complete in my console.
Currently the cobigen generate command only accepts forward slashes (which don't support auto complete on Windows).

**Comment by Zylesto** [comment] 2022-09-16 08:10
I tried to reproduce this error, however backslashes and autocompletion work for me on windows cmd. I was using devon version 2022.08.001 and cobigen version 2021.12.006. 
However it didn't work with git bash, as backward slashes are an escape character and the backward slash is dropped, as mentioned here: https://stackoverflow.com/questions/40396613/forward-slash-vs-backward-slash-for-file-path-in-git-bash

**Comment by Zylesto** [comment] 2022-09-16 09:48
The issue seems to be related to devon, as only **_devon cobigen g example\path_** does not work. Please use _**cobigen g example\path**_ instead. 
I will close this ticket and open ticket regarding this issue in the devon ide repo.

**Closed by Zylesto** 2022-09-16 09:48 UTC
Labels: good first issue, app:cli, Team_CobiGen_Templates
