### ISSUE TITLE
FileSystemNotFoundException blocking cobigen-cli

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1110] opened 2020-02-25 09:32 UTC
### Expected behavior

As a cobigen user, I want to be able to use `cobigen-cli` so that I can generate code independent of any IDE such as Eclipse.

### Actual behavior

```
cg generate api/src/main/java/...package.../common/api/...BO-interface....java
[INFO ] As this is your first execution of the CLI, we are going to download the needed dependencies. Please be patient...

[WARN] Maven will be executed in interactive mode, but no input stream has been configured for this MavenInvoker instance.
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................
java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at com.devonfw.cobigen.cli.utils.CobiGenUtils.resolveTemplateUtilClassesFromJar(CobiGenUtils.java:135)
	at com.devonfw.cobigen.cli.utils.CobiGenUtils.getTemplates(CobiGenUtils.java:218)
	at com.devonfw.cobigen.cli.utils.CobiGenUtils.initializeCobiGen(CobiGenUtils.java:195)
	at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:119)
	at com.devonfw.cobigen.cli.commands.GenerateCommand.call(GenerateCommand.java:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1680)
	at picocli.CommandLine.access$900(CommandLine.java:144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2038)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2005)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1872)
	at picocli.CommandLine.execute(CommandLine.java:1801)
	at com.devonfw.cobigen.cli.CobiGenCLI.main(CobiGenCLI.java:43)
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install cobigen-cli with devonfw-ide
2. I additionally replaced the devon4j templates with my custom templates as suggested by @jdiazgon 

### Related/Dependent Issues
https://stackoverflow.com/questions/25032716/getting-filesystemnotfoundexception-from-zipfilesystemprovider-when-creating-a-p

### Comments/Hints:
IMHO a bug in CobiGen.

### Affected version:

* OS: Mac

**Comment by jdiazgon** [comment] 2020-02-26 07:45
The issue is on [this line](https://github.com/devonfw/cobigen/blob/master/cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/utils/CobiGenUtils.java#L134). Most probably we need to add:

```Java
else {
            Map<String, String> env = new HashMap<>();
            env.put("create", "true");

            URI uri = URI.create(contextConfigurationLocation.toString());
            FileSystem zipfs = FileSystems.newFileSystem(uri, env);
            Path contextPath= Paths.get(uri);
        }
```
But first I would need to know how to reproduce this: How have you replaced the devon4j templates with your own ones? Have you changed the pom.xml or the classpath.txt? And are your custom templates in a Jar?

**Comment by hohwille** [comment] 2020-02-27 14:01
Feedback:
* custom templates are in a JAR
* this is installed via maven (to my local repo)
* I updated `cobigen-cli/pom.xml` accordingly
* I deleted `classPath.txt` and verified that it gets regenerated from `pom.xml`
* Verified that my custom templates are properly referenced in `classPath.txt`
* devon4j templates are not anymore in `classPath.txt`

**Comment by hohwille** [comment] 2020-02-27 14:03
As you can read in the stackoverflow link it seems that your code in CobiGen does not properly create the Zip filesystem before using it. Is that possible? What is the difference when using custom templates instead of default ones? Does it probably make a difference if the templates JAR has been created with Java8 or Java11?

**Comment by hohwille** [comment] 2020-02-27 14:04
At least in this project, I am still using Java 1.8. The templates have also been build with that JDK.

**Comment by jdiazgon** [comment] 2020-02-27 16:35
As far as I can understand, there is an `if` condition which to me always returned `true` and it executed code that is working, and in your case the `if` went to code that is failing. [Here](https://github.com/devonfw/cobigen/blob/master/cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/utils/CobiGenUtils.java#L113)you can see the code:

``` Java
  List<Class<?>> resolveTemplateUtilClassesFromJar(File templatesJar) throws IOException {
        final List<Class<?>> result = new LinkedList<>();
        ClassLoader inputClassLoader =
            URLClassLoader.newInstance(new URL[] { templatesJar.toURI().toURL() }, getClass().getClassLoader());
        URL contextConfigurationLocation = inputClassLoader.getResource("context.xml");
        if (contextConfigurationLocation == null
            || contextConfigurationLocation.getPath().endsWith("target/classes/context.xml")) {
            contextConfigurationLocation = inputClassLoader.getResource("src/main/templates/context.xml");
```
Inside your custom templates jar, is the file `context.xml` on the root? It should be on `src/main/templates/context.xml` to work well.

**Comment by hohwille** [comment] 2020-02-28 10:31
Thanks for your investigation. This could really help us to make progress here and find a workaround.

> Inside your custom templates jar, is the file context.xml on the root?

Yes:
```
jar vtf target/CobiGen_Templates-2.4.0-SNAPSHOT.jar
...
  4951 Fri Feb 21 12:40:04 CET 2020 context.xml
  1666 Fri Feb 21 12:40:04 CET 2020 crud/templates.xml
  8155 Fri Feb 21 12:40:04 CET 2020 crud/functions.ftl
...
```

> It should be on src/main/templates/context.xml to work well. Obviously this is a bug that we must fix, but can you try meanwhile that workaround?

Thanks for the hint. I will try this workaround and let you know if this helps.

**Comment by hohwille** [comment] 2020-02-28 10:34
Indeed:
```
jar vft ~/.m2/repository/com/devonfw/cobigen/templates-devon4j/3.1.8/templates-devon4j-3.1.8.jar | grep context.xml
  9572 Fri Jan 10 13:59:16 CET 2020 src/main/templates/context.xml
```
Seems hackish, but if that helps me for the moment to proceed, I will do it alike.

**Comment by hohwille** [comment] 2020-02-28 10:42
Awesome. This resolved my problem. However, this just leads me to the next error in cobigen-cli. I will file another issue for that.
So we have a workaround for this problem. You could even close this issue and consider it as a feature that templates have to be located in `src/main/templates/*` inside the JAR (even though it seems a bit odd).

**Comment by maybeec** [comment] 2020-02-28 14:33
This is currently in progress to be resolved by @jan-vcapgemini .

**Comment by jdiazgon** [comment] 2020-03-03 13:03
@jan-vcapgemini I am going to add a quick fix as I want to release today. But my code should be refactored with your fix, that as of now seems you are doing a good job.

**Closed** 2020-04-27 15:17 UTC
Labels: bug, cobigen-cli
